################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/carrier_phy.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/clkref_phy.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/hdx.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/hdx_coding.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/timeout.c \
C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/txct_phy.c 

OBJS += \
./Middlewares/SIC/lfreader/driver/portunas/carrier_phy.o \
./Middlewares/SIC/lfreader/driver/portunas/clkref_phy.o \
./Middlewares/SIC/lfreader/driver/portunas/hdx.o \
./Middlewares/SIC/lfreader/driver/portunas/hdx_coding.o \
./Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.o \
./Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.o \
./Middlewares/SIC/lfreader/driver/portunas/timeout.o \
./Middlewares/SIC/lfreader/driver/portunas/txct_phy.o 

C_DEPS += \
./Middlewares/SIC/lfreader/driver/portunas/carrier_phy.d \
./Middlewares/SIC/lfreader/driver/portunas/clkref_phy.d \
./Middlewares/SIC/lfreader/driver/portunas/hdx.d \
./Middlewares/SIC/lfreader/driver/portunas/hdx_coding.d \
./Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.d \
./Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.d \
./Middlewares/SIC/lfreader/driver/portunas/timeout.d \
./Middlewares/SIC/lfreader/driver/portunas/txct_phy.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/SIC/lfreader/driver/portunas/carrier_phy.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/carrier_phy.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/carrier_phy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/clkref_phy.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/clkref_phy.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/clkref_phy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/hdx.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/hdx.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/hdx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/hdx_coding.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/hdx_coding.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/hdx_coding.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/timeout.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/timeout.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/timeout.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/SIC/lfreader/driver/portunas/txct_phy.o: C:/Users/ASUS/Downloads/portunas_fw2(defult)\ (1)/portunas_fw2/Middlewares/SIC/lfreader/driver/portunas/txct_phy.c Middlewares/SIC/lfreader/driver/portunas/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L452xx -c -I../. -I../../../../Application/System/include -I../../../../Application/System/board/nucleo_l452re -I../../../../Application/MicroReader/Inc -I../../../../Application/MaxArch -I../../../../Application/Main/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Drivers/CMSIS/Include -I../../../../Application/USBDevice/App -I../../../../Application/USBDevice/Target -I../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../Middlewares/SIC/max/include -I../../../../Middlewares/SIC/lfreader/include -I../../../../Middlewares/SIC/lfreader/port/portunas -I../../../../Utilities/circular_buffer -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/SIC/lfreader/driver/portunas/txct_phy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-SIC-2f-lfreader-2f-driver-2f-portunas

clean-Middlewares-2f-SIC-2f-lfreader-2f-driver-2f-portunas:
	-$(RM) ./Middlewares/SIC/lfreader/driver/portunas/carrier_phy.cyclo ./Middlewares/SIC/lfreader/driver/portunas/carrier_phy.d ./Middlewares/SIC/lfreader/driver/portunas/carrier_phy.o ./Middlewares/SIC/lfreader/driver/portunas/carrier_phy.su ./Middlewares/SIC/lfreader/driver/portunas/clkref_phy.cyclo ./Middlewares/SIC/lfreader/driver/portunas/clkref_phy.d ./Middlewares/SIC/lfreader/driver/portunas/clkref_phy.o ./Middlewares/SIC/lfreader/driver/portunas/clkref_phy.su ./Middlewares/SIC/lfreader/driver/portunas/hdx.cyclo ./Middlewares/SIC/lfreader/driver/portunas/hdx.d ./Middlewares/SIC/lfreader/driver/portunas/hdx.o ./Middlewares/SIC/lfreader/driver/portunas/hdx.su ./Middlewares/SIC/lfreader/driver/portunas/hdx_coding.cyclo ./Middlewares/SIC/lfreader/driver/portunas/hdx_coding.d ./Middlewares/SIC/lfreader/driver/portunas/hdx_coding.o ./Middlewares/SIC/lfreader/driver/portunas/hdx_coding.su ./Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.cyclo ./Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.d ./Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.o ./Middlewares/SIC/lfreader/driver/portunas/hdx_in_phy.su ./Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.cyclo ./Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.d ./Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.o ./Middlewares/SIC/lfreader/driver/portunas/ioctrl_phy.su ./Middlewares/SIC/lfreader/driver/portunas/timeout.cyclo ./Middlewares/SIC/lfreader/driver/portunas/timeout.d ./Middlewares/SIC/lfreader/driver/portunas/timeout.o ./Middlewares/SIC/lfreader/driver/portunas/timeout.su ./Middlewares/SIC/lfreader/driver/portunas/txct_phy.cyclo ./Middlewares/SIC/lfreader/driver/portunas/txct_phy.d ./Middlewares/SIC/lfreader/driver/portunas/txct_phy.o ./Middlewares/SIC/lfreader/driver/portunas/txct_phy.su

.PHONY: clean-Middlewares-2f-SIC-2f-lfreader-2f-driver-2f-portunas

